# List

In [3]:
colors=["red","green"]

In [4]:
colors.remove("red")


In [5]:
colors


['green']

In [7]:
colors.insert(0,"yellow")

In [8]:
colors


['yellow', 'green']

In [9]:
colors.index("green")


1

In [10]:
l1=[1,2,4,5,6,7,7,4]

In [12]:
l1.count(3)

0

In [13]:
l1.sort(reverse=True)

In [14]:
l1


[7, 7, 6, 5, 4, 4, 2, 1]

In [15]:
### insert a new number in secomd position

In [16]:
list1=[12,22,44,33]

In [17]:
list1.append(2)

In [18]:
list1.insert(1,55)

In [19]:
list1

[12, 55, 22, 44, 33, 2]

In [20]:
l2=["redd","green","yellow"]
l2.extend(l1)

In [21]:
l2

['redd', 'green', 'yellow', 7, 7, 6, 5, 4, 4, 2, 1]

In [22]:
print(l2.pop())

1


In [23]:
# ARRAY

In [25]:
import numpy as np

In [26]:
a=np.array([1,2,4,3,5])

In [28]:
b=np.array([[1,2],[3,4]])

In [29]:
b

array([[1, 2],
       [3, 4]])

In [32]:
d=np.array([[1,4],[33,4]])

In [33]:
c=np.add(d,b)
print(c)

[[ 2  6]
 [36  8]]


In [34]:
np.subtract(d,b)

array([[ 0,  2],
       [30,  0]])

In [36]:
np.linalg.inv(d)

array([[-0.03125  ,  0.03125  ],
       [ 0.2578125, -0.0078125]])

In [37]:
np.transpose(d)

array([[ 1, 33],
       [ 4,  4]])

In [38]:
np.linalg.det(b)

np.float64(-2.0000000000000004)

In [39]:
np.linalg.matrix_rank(b)

np.int64(2)

In [42]:
l1=np.array([[1,1],[3,4]])
np.linalg.matrix_rank(l1)

np.int64(2)

create two 3x3 matrices A+B.find the determinants of a and b.find rank of a and b

In [43]:
m1=np.array([[1,3,4],[3,2,3],[5,3,4]])
m2=np.array([[5,3,5],[3,9,4],[2,3,5]])

In [45]:
addd=np.add(m1,m2)
mul=np.dot(m1,m2)
detm1=np.linalg.det(m1)
detm2=np.linalg.det(m2)
rank1=np.linalg.matrix_rank(m1)
rank2=np.linalg.matrix_rank(m2)

In [46]:
addd
mul
detm1
detm2
rank1
rank2

np.int64(3)